// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vsix_demo1
{
    internal sealed partial class Vsix
    {
        public const string Id = "vsix_demo1.117c5265-e011-4e02-a87e-bae810f59ad7";
        public const string Name = "vsix_demo1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
