// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RTTIScanner.vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "RTTIScanner.117c5265-e011-4e02-a87e-bae810f59ad7";
        public const string Name = "RTTIScanner";
        public const string Description = @"A visual studio extension that scans the RTTI of given memory.";
        public const string Language = "en-US";
        public const string Version = "1.3.2";
        public const string Author = "Anie1337";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
